name: whisp
description: "Whisp"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.8+9

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^10.0.0
  hive_ce: ^2.15.1
  hive_ce_flutter: 
  get_it: ^9.2.0
  injectable: ^2.7.1+2
  injectable_generator: ^2.11.1
  cryptography: ^2.9.0
  cryptography_flutter: ^2.3.4
  auto_route_generator: ^10.4.0
  auto_route: ^11.1.0
  flutter_bloc: ^9.1.1
  meta: ^1.17.0
  theme_tailor: ^3.1.2
  theme_tailor_annotation: ^3.1.2
  http: ^1.6.0
  dartz: ^0.10.1
  tor_hidden_service:
    git:
      url: https://github.com/AntoniPochopien/tor_hidden_service.git
      ref: support-16kb-pages
      path: tor_hidden_service
  uuid: ^4.5.2
  drift: ^2.22.1
  sqlite3_flutter_libs: ^0.5.28
  path_provider: ^2.1.5
  path: ^1.9.1
  qr_flutter: ^4.1.0
  share_plus: ^12.0.1
  mobile_scanner: ^7.1.4
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  libsignal_protocol_dart: ^0.7.4
  flutter_local_notifications: ^19.5.0
  url_launcher: ^6.3.2
  flutter_foreground_task: ^9.1.0
  local_auth: ^3.0.0
  pinput: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  hive_ce_generator: ^1.10.1
  drift_dev: ^2.22.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/